import { createSlice, createEntityAdapter } from '@reduxjs/toolkit';
import {
  fetchStudents,
  addStudentAsync,
  updateStudentAsync,
  deleteStudentAsync,
} from './studentsThunks';

// Create adapter with sorting by name
const studentsAdapter = createEntityAdapter({
  sortComparer: (a, b) => a.name.localeCompare(b.name),
});

// Initial state using adapter.getInitialState
const initialState = studentsAdapter.getInitialState({
  status: 'idle',
  error: null,
});

const studentsSlice = createSlice({
  name: 'students',
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder
      .addCase(fetchStudents.pending, (state) => {
        state.status = 'loading';
        state.error = null;
      })
      .addCase(fetchStudents.fulfilled, (state, { payload }) => {
        state.status = 'succeeded';
        studentsAdapter.setAll(state, payload);
      })
      .addCase(fetchStudents.rejected, (state, { payload }) => {
        state.status = 'failed';
        state.error = payload;
      })
      .addCase(addStudentAsync.fulfilled, (state, { payload }) => {
        studentsAdapter.addOne(state, payload);
      })
      .addCase(updateStudentAsync.fulfilled, (state, { payload }) => {
        studentsAdapter.upsertOne(state, payload);
      })
      .addCase(deleteStudentAsync.fulfilled, (state, { payload }) => {
        studentsAdapter.removeOne(state, payload);
      });
  },
});

// Export selectors generated by the adapter
export const {
  selectAll: selectAllStudents,
  selectById: selectStudentById,
  selectTotal: selectStudentCount,
} = studentsAdapter.getSelectors((state) => state.students);

export default studentsSlice.reducer;
